// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'diagnostics.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_compression_kind`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

String coreVersion() => PhotonLinkCoreApi.instance.api.crateApiCoreVersion();

String sha256Hex({required List<int> data}) =>
    PhotonLinkCoreApi.instance.api.crateApiSha256Hex(data: data);

bool sha256Verify({required List<int> data, required String expected}) =>
    PhotonLinkCoreApi.instance.api
        .crateApiSha256Verify(data: data, expected: expected);

int crc32Compute({required List<int> data}) =>
    PhotonLinkCoreApi.instance.api.crateApiCrc32Compute(data: data);

bool crc32Validate({required List<int> data, required int expected}) =>
    PhotonLinkCoreApi.instance.api
        .crateApiCrc32Validate(data: data, expected: expected);

String encodePl2DataFrame(
        {required String sessionId,
        required int chunkId,
        required int totalChunks,
        required List<int> payload}) =>
    PhotonLinkCoreApi.instance.api.crateApiEncodePl2DataFrame(
        sessionId: sessionId,
        chunkId: chunkId,
        totalChunks: totalChunks,
        payload: payload);

Pl2FrameDto decodePl2Frame({required String raw}) =>
    PhotonLinkCoreApi.instance.api.crateApiDecodePl2Frame(raw: raw);

Uint8List encodePlcmFrame({required PlcmFrameDto frame}) =>
    PhotonLinkCoreApi.instance.api.crateApiEncodePlcmFrame(frame: frame);

PlcmFrameDto decodePlcmFrame({required List<int> bytes}) =>
    PhotonLinkCoreApi.instance.api.crateApiDecodePlcmFrame(bytes: bytes);

Uint8List encodePlosFrame({required PlosFrameDto frame}) =>
    PhotonLinkCoreApi.instance.api.crateApiEncodePlosFrame(frame: frame);

PlosFrameDto decodePlosFrame({required List<int> bytes}) =>
    PhotonLinkCoreApi.instance.api.crateApiDecodePlosFrame(bytes: bytes);

List<DataChunkDto> chunkSplit(
        {required List<int> data,
        required String sessionId,
        required int chunkSize}) =>
    PhotonLinkCoreApi.instance.api.crateApiChunkSplit(
        data: data, sessionId: sessionId, chunkSize: chunkSize);

Uint8List chunkMerge({required List<DataChunkDto> chunks}) =>
    PhotonLinkCoreApi.instance.api.crateApiChunkMerge(chunks: chunks);

ReconstructionHandle reconstructionNew() =>
    PhotonLinkCoreApi.instance.api.crateApiReconstructionNew();

CompressionOutputDto compressData(
        {required List<int> input, required String kind}) =>
    PhotonLinkCoreApi.instance.api
        .crateApiCompressData(input: input, kind: kind);

CompressionOutputDto decompressData(
        {required List<int> input,
        required String kind,
        required int originalSize}) =>
    PhotonLinkCoreApi.instance.api.crateApiDecompressData(
        input: input, kind: kind, originalSize: originalSize);

Uint8List encryptData(
        {required List<int> plaintext, required List<int> sessionKey}) =>
    PhotonLinkCoreApi.instance.api
        .crateApiEncryptData(plaintext: plaintext, sessionKey: sessionKey);

Uint8List decryptData(
        {required List<int> wire, required List<int> sessionKey}) =>
    PhotonLinkCoreApi.instance.api
        .crateApiDecryptData(wire: wire, sessionKey: sessionKey);

QualityScoreOutput calculateQualityScore({required QualityScoreInput input}) =>
    PhotonLinkCoreApi.instance.api.crateApiCalculateQualityScore(input: input);

List<Uint8List> fecEncodeBlock(
        {required List<Uint8List> dataSymbols,
        required int parityCount,
        required int symbolLength}) =>
    PhotonLinkCoreApi.instance.api.crateApiFecEncodeBlock(
        dataSymbols: dataSymbols,
        parityCount: parityCount,
        symbolLength: symbolLength);

List<Uint8List>? fecDecodeBlock(
        {required int dataCount,
        required int parityCount,
        required int symbolLength,
        required List<int> erasures,
        required List<int> availableKeys,
        required List<Uint8List> availableValues}) =>
    PhotonLinkCoreApi.instance.api.crateApiFecDecodeBlock(
        dataCount: dataCount,
        parityCount: parityCount,
        symbolLength: symbolLength,
        erasures: erasures,
        availableKeys: availableKeys,
        availableValues: availableValues);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ReconstructionHandle>>
abstract class ReconstructionHandle implements RustOpaqueInterface {
  Future<bool> ingestData({required DataChunkDto chunk});

  Future<bool> isComplete();

  Future<Uint8List?> rebuild();

  Future<void> reset();

  Future<bool> setMetadata(
      {required String sessionId, required int totalChunks});
}

class CompressionOutputDto {
  final int originalSize;
  final int outputSize;
  final Uint8List bytes;

  const CompressionOutputDto({
    required this.originalSize,
    required this.outputSize,
    required this.bytes,
  });

  @override
  int get hashCode =>
      originalSize.hashCode ^ outputSize.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CompressionOutputDto &&
          runtimeType == other.runtimeType &&
          originalSize == other.originalSize &&
          outputSize == other.outputSize &&
          bytes == other.bytes;
}

class DataChunkDto {
  final String sessionId;
  final int chunkId;
  final int totalChunks;
  final Uint8List payload;

  const DataChunkDto({
    required this.sessionId,
    required this.chunkId,
    required this.totalChunks,
    required this.payload,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      chunkId.hashCode ^
      totalChunks.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataChunkDto &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          chunkId == other.chunkId &&
          totalChunks == other.totalChunks &&
          payload == other.payload;
}

class Pl2FrameDto {
  final String packetType;
  final String sessionId;
  final int seq;
  final int total;
  final Uint8List payload;

  const Pl2FrameDto({
    required this.packetType,
    required this.sessionId,
    required this.seq,
    required this.total,
    required this.payload,
  });

  @override
  int get hashCode =>
      packetType.hashCode ^
      sessionId.hashCode ^
      seq.hashCode ^
      total.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Pl2FrameDto &&
          runtimeType == other.runtimeType &&
          packetType == other.packetType &&
          sessionId == other.sessionId &&
          seq == other.seq &&
          total == other.total &&
          payload == other.payload;
}

class PlcmFrameDto {
  final int protocolVersion;
  final String sessionId;
  final int frameId;
  final int packetId;
  final int packetType;
  final int totalPackets;
  final int gridSize;
  final int bitsPerChannel;
  final Uint8List payload;
  final int checksum;

  const PlcmFrameDto({
    required this.protocolVersion,
    required this.sessionId,
    required this.frameId,
    required this.packetId,
    required this.packetType,
    required this.totalPackets,
    required this.gridSize,
    required this.bitsPerChannel,
    required this.payload,
    required this.checksum,
  });

  @override
  int get hashCode =>
      protocolVersion.hashCode ^
      sessionId.hashCode ^
      frameId.hashCode ^
      packetId.hashCode ^
      packetType.hashCode ^
      totalPackets.hashCode ^
      gridSize.hashCode ^
      bitsPerChannel.hashCode ^
      payload.hashCode ^
      checksum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlcmFrameDto &&
          runtimeType == other.runtimeType &&
          protocolVersion == other.protocolVersion &&
          sessionId == other.sessionId &&
          frameId == other.frameId &&
          packetId == other.packetId &&
          packetType == other.packetType &&
          totalPackets == other.totalPackets &&
          gridSize == other.gridSize &&
          bitsPerChannel == other.bitsPerChannel &&
          payload == other.payload &&
          checksum == other.checksum;
}

class PlosFrameDto {
  final int protocolVersion;
  final String sessionId;
  final int streamId;
  final int frameId;
  final int packetId;
  final int packetType;
  final int totalPackets;
  final int syncMarker;
  final BigInt timestamp;
  final int gridSize;
  final int bitsPerCell;
  final Uint8List payload;
  final int checksum;

  const PlosFrameDto({
    required this.protocolVersion,
    required this.sessionId,
    required this.streamId,
    required this.frameId,
    required this.packetId,
    required this.packetType,
    required this.totalPackets,
    required this.syncMarker,
    required this.timestamp,
    required this.gridSize,
    required this.bitsPerCell,
    required this.payload,
    required this.checksum,
  });

  @override
  int get hashCode =>
      protocolVersion.hashCode ^
      sessionId.hashCode ^
      streamId.hashCode ^
      frameId.hashCode ^
      packetId.hashCode ^
      packetType.hashCode ^
      totalPackets.hashCode ^
      syncMarker.hashCode ^
      timestamp.hashCode ^
      gridSize.hashCode ^
      bitsPerCell.hashCode ^
      payload.hashCode ^
      checksum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlosFrameDto &&
          runtimeType == other.runtimeType &&
          protocolVersion == other.protocolVersion &&
          sessionId == other.sessionId &&
          streamId == other.streamId &&
          frameId == other.frameId &&
          packetId == other.packetId &&
          packetType == other.packetType &&
          totalPackets == other.totalPackets &&
          syncMarker == other.syncMarker &&
          timestamp == other.timestamp &&
          gridSize == other.gridSize &&
          bitsPerCell == other.bitsPerCell &&
          payload == other.payload &&
          checksum == other.checksum;
}
