// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Input for quality score calculation (mirrors Dart FrameDiagnostics + EnvironmentProfile).
class QualityScoreInput {
  final int framesReceived;
  final int framesCorrupted;
  final int framesLost;
  final int missingPacketCount;
  final int framesRetried;
  final double detectionAccuracy;
  final double avgBrightness;
  final double detectionSuccessRate;
  final int fecParityGenerated;
  final double fecRecoverySuccessRate;
  final double fecParityEfficiency;
  final double fecOverhead;

  const QualityScoreInput({
    required this.framesReceived,
    required this.framesCorrupted,
    required this.framesLost,
    required this.missingPacketCount,
    required this.framesRetried,
    required this.detectionAccuracy,
    required this.avgBrightness,
    required this.detectionSuccessRate,
    required this.fecParityGenerated,
    required this.fecRecoverySuccessRate,
    required this.fecParityEfficiency,
    required this.fecOverhead,
  });

  @override
  int get hashCode =>
      framesReceived.hashCode ^
      framesCorrupted.hashCode ^
      framesLost.hashCode ^
      missingPacketCount.hashCode ^
      framesRetried.hashCode ^
      detectionAccuracy.hashCode ^
      avgBrightness.hashCode ^
      detectionSuccessRate.hashCode ^
      fecParityGenerated.hashCode ^
      fecRecoverySuccessRate.hashCode ^
      fecParityEfficiency.hashCode ^
      fecOverhead.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QualityScoreInput &&
          runtimeType == other.runtimeType &&
          framesReceived == other.framesReceived &&
          framesCorrupted == other.framesCorrupted &&
          framesLost == other.framesLost &&
          missingPacketCount == other.missingPacketCount &&
          framesRetried == other.framesRetried &&
          detectionAccuracy == other.detectionAccuracy &&
          avgBrightness == other.avgBrightness &&
          detectionSuccessRate == other.detectionSuccessRate &&
          fecParityGenerated == other.fecParityGenerated &&
          fecRecoverySuccessRate == other.fecRecoverySuccessRate &&
          fecParityEfficiency == other.fecParityEfficiency &&
          fecOverhead == other.fecOverhead;
}

/// Output quality score with factor breakdown.
class QualityScoreOutput {
  final double score;
  final double frameLossFactor;
  final double decodeErrorFactor;
  final double retryFactor;
  final double detectionStabilityFactor;
  final double brightnessFactor;
  final double recoveryFactor;

  const QualityScoreOutput({
    required this.score,
    required this.frameLossFactor,
    required this.decodeErrorFactor,
    required this.retryFactor,
    required this.detectionStabilityFactor,
    required this.brightnessFactor,
    required this.recoveryFactor,
  });

  @override
  int get hashCode =>
      score.hashCode ^
      frameLossFactor.hashCode ^
      decodeErrorFactor.hashCode ^
      retryFactor.hashCode ^
      detectionStabilityFactor.hashCode ^
      brightnessFactor.hashCode ^
      recoveryFactor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QualityScoreOutput &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          frameLossFactor == other.frameLossFactor &&
          decodeErrorFactor == other.decodeErrorFactor &&
          retryFactor == other.retryFactor &&
          detectionStabilityFactor == other.detectionStabilityFactor &&
          brightnessFactor == other.brightnessFactor &&
          recoveryFactor == other.recoveryFactor;
}
