// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'diagnostics.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class PhotonLinkCoreApi extends BaseEntrypoint<PhotonLinkCoreApiApi,
    PhotonLinkCoreApiApiImpl, PhotonLinkCoreApiWire> {
  @internal
  static final instance = PhotonLinkCoreApi._();

  PhotonLinkCoreApi._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    PhotonLinkCoreApiApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required PhotonLinkCoreApiApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<PhotonLinkCoreApiApiImpl, PhotonLinkCoreApiWire>
      get apiImplConstructor => PhotonLinkCoreApiApiImpl.new;

  @override
  WireConstructor<PhotonLinkCoreApiWire> get wireConstructor =>
      PhotonLinkCoreApiWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1326308692;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'photonlink_core',
    ioDirectory: '../photonlink_core/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class PhotonLinkCoreApiApi extends BaseApi {
  Future<bool> crateApiReconstructionHandleIngestData(
      {required ReconstructionHandle that, required DataChunkDto chunk});

  Future<bool> crateApiReconstructionHandleIsComplete(
      {required ReconstructionHandle that});

  Future<Uint8List?> crateApiReconstructionHandleRebuild(
      {required ReconstructionHandle that});

  Future<void> crateApiReconstructionHandleReset(
      {required ReconstructionHandle that});

  Future<bool> crateApiReconstructionHandleSetMetadata(
      {required ReconstructionHandle that,
      required String sessionId,
      required int totalChunks});

  QualityScoreOutput crateApiCalculateQualityScore(
      {required QualityScoreInput input});

  Uint8List crateApiChunkMerge({required List<DataChunkDto> chunks});

  List<DataChunkDto> crateApiChunkSplit(
      {required List<int> data,
      required String sessionId,
      required int chunkSize});

  CompressionOutputDto crateApiCompressData(
      {required List<int> input, required String kind});

  String crateApiCoreVersion();

  int crateApiCrc32Compute({required List<int> data});

  bool crateApiCrc32Validate({required List<int> data, required int expected});

  Pl2FrameDto crateApiDecodePl2Frame({required String raw});

  PlcmFrameDto crateApiDecodePlcmFrame({required List<int> bytes});

  PlosFrameDto crateApiDecodePlosFrame({required List<int> bytes});

  CompressionOutputDto crateApiDecompressData(
      {required List<int> input,
      required String kind,
      required int originalSize});

  Uint8List crateApiDecryptData(
      {required List<int> wire, required List<int> sessionKey});

  String crateApiEncodePl2DataFrame(
      {required String sessionId,
      required int chunkId,
      required int totalChunks,
      required List<int> payload});

  Uint8List crateApiEncodePlcmFrame({required PlcmFrameDto frame});

  Uint8List crateApiEncodePlosFrame({required PlosFrameDto frame});

  Uint8List crateApiEncryptData(
      {required List<int> plaintext, required List<int> sessionKey});

  List<Uint8List>? crateApiFecDecodeBlock(
      {required int dataCount,
      required int parityCount,
      required int symbolLength,
      required List<int> erasures,
      required List<int> availableKeys,
      required List<Uint8List> availableValues});

  List<Uint8List> crateApiFecEncodeBlock(
      {required List<Uint8List> dataSymbols,
      required int parityCount,
      required int symbolLength});

  ReconstructionHandle crateApiReconstructionNew();

  String crateApiSha256Hex({required List<int> data});

  bool crateApiSha256Verify(
      {required List<int> data, required String expected});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ReconstructionHandle;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ReconstructionHandle;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ReconstructionHandlePtr;
}

class PhotonLinkCoreApiApiImpl extends PhotonLinkCoreApiApiImplPlatform
    implements PhotonLinkCoreApiApi {
  PhotonLinkCoreApiApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiReconstructionHandleIngestData(
      {required ReconstructionHandle that, required DataChunkDto chunk}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
            that, serializer);
        sse_encode_box_autoadd_data_chunk_dto(chunk, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReconstructionHandleIngestDataConstMeta,
      argValues: [that, chunk],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReconstructionHandleIngestDataConstMeta =>
      const TaskConstMeta(
        debugName: "ReconstructionHandle_ingest_data",
        argNames: ["that", "chunk"],
      );

  @override
  Future<bool> crateApiReconstructionHandleIsComplete(
      {required ReconstructionHandle that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReconstructionHandleIsCompleteConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReconstructionHandleIsCompleteConstMeta =>
      const TaskConstMeta(
        debugName: "ReconstructionHandle_is_complete",
        argNames: ["that"],
      );

  @override
  Future<Uint8List?> crateApiReconstructionHandleRebuild(
      {required ReconstructionHandle that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReconstructionHandleRebuildConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReconstructionHandleRebuildConstMeta =>
      const TaskConstMeta(
        debugName: "ReconstructionHandle_rebuild",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiReconstructionHandleReset(
      {required ReconstructionHandle that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReconstructionHandleResetConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReconstructionHandleResetConstMeta =>
      const TaskConstMeta(
        debugName: "ReconstructionHandle_reset",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiReconstructionHandleSetMetadata(
      {required ReconstructionHandle that,
      required String sessionId,
      required int totalChunks}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
            that, serializer);
        sse_encode_String(sessionId, serializer);
        sse_encode_u_32(totalChunks, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReconstructionHandleSetMetadataConstMeta,
      argValues: [that, sessionId, totalChunks],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReconstructionHandleSetMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "ReconstructionHandle_set_metadata",
        argNames: ["that", "sessionId", "totalChunks"],
      );

  @override
  QualityScoreOutput crateApiCalculateQualityScore(
      {required QualityScoreInput input}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_quality_score_input(input, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_quality_score_output,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCalculateQualityScoreConstMeta,
      argValues: [input],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCalculateQualityScoreConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_quality_score",
        argNames: ["input"],
      );

  @override
  Uint8List crateApiChunkMerge({required List<DataChunkDto> chunks}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_data_chunk_dto(chunks, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiChunkMergeConstMeta,
      argValues: [chunks],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiChunkMergeConstMeta => const TaskConstMeta(
        debugName: "chunk_merge",
        argNames: ["chunks"],
      );

  @override
  List<DataChunkDto> crateApiChunkSplit(
      {required List<int> data,
      required String sessionId,
      required int chunkSize}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_String(sessionId, serializer);
        sse_encode_u_32(chunkSize, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_data_chunk_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiChunkSplitConstMeta,
      argValues: [data, sessionId, chunkSize],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiChunkSplitConstMeta => const TaskConstMeta(
        debugName: "chunk_split",
        argNames: ["data", "sessionId", "chunkSize"],
      );

  @override
  CompressionOutputDto crateApiCompressData(
      {required List<int> input, required String kind}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(input, serializer);
        sse_encode_String(kind, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_compression_output_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCompressDataConstMeta,
      argValues: [input, kind],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCompressDataConstMeta => const TaskConstMeta(
        debugName: "compress_data",
        argNames: ["input", "kind"],
      );

  @override
  String crateApiCoreVersion() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCoreVersionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreVersionConstMeta => const TaskConstMeta(
        debugName: "core_version",
        argNames: [],
      );

  @override
  int crateApiCrc32Compute({required List<int> data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_32,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCrc32ComputeConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCrc32ComputeConstMeta => const TaskConstMeta(
        debugName: "crc32_compute",
        argNames: ["data"],
      );

  @override
  bool crateApiCrc32Validate({required List<int> data, required int expected}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_u_32(expected, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCrc32ValidateConstMeta,
      argValues: [data, expected],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCrc32ValidateConstMeta => const TaskConstMeta(
        debugName: "crc32_validate",
        argNames: ["data", "expected"],
      );

  @override
  Pl2FrameDto crateApiDecodePl2Frame({required String raw}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(raw, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_pl_2_frame_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDecodePl2FrameConstMeta,
      argValues: [raw],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDecodePl2FrameConstMeta => const TaskConstMeta(
        debugName: "decode_pl2_frame",
        argNames: ["raw"],
      );

  @override
  PlcmFrameDto crateApiDecodePlcmFrame({required List<int> bytes}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_plcm_frame_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDecodePlcmFrameConstMeta,
      argValues: [bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDecodePlcmFrameConstMeta => const TaskConstMeta(
        debugName: "decode_plcm_frame",
        argNames: ["bytes"],
      );

  @override
  PlosFrameDto crateApiDecodePlosFrame({required List<int> bytes}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_plos_frame_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDecodePlosFrameConstMeta,
      argValues: [bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDecodePlosFrameConstMeta => const TaskConstMeta(
        debugName: "decode_plos_frame",
        argNames: ["bytes"],
      );

  @override
  CompressionOutputDto crateApiDecompressData(
      {required List<int> input,
      required String kind,
      required int originalSize}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(input, serializer);
        sse_encode_String(kind, serializer);
        sse_encode_u_32(originalSize, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_compression_output_dto,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDecompressDataConstMeta,
      argValues: [input, kind, originalSize],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDecompressDataConstMeta => const TaskConstMeta(
        debugName: "decompress_data",
        argNames: ["input", "kind", "originalSize"],
      );

  @override
  Uint8List crateApiDecryptData(
      {required List<int> wire, required List<int> sessionKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(wire, serializer);
        sse_encode_list_prim_u_8_loose(sessionKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiDecryptDataConstMeta,
      argValues: [wire, sessionKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDecryptDataConstMeta => const TaskConstMeta(
        debugName: "decrypt_data",
        argNames: ["wire", "sessionKey"],
      );

  @override
  String crateApiEncodePl2DataFrame(
      {required String sessionId,
      required int chunkId,
      required int totalChunks,
      required List<int> payload}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_u_32(chunkId, serializer);
        sse_encode_u_32(totalChunks, serializer);
        sse_encode_list_prim_u_8_loose(payload, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiEncodePl2DataFrameConstMeta,
      argValues: [sessionId, chunkId, totalChunks, payload],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEncodePl2DataFrameConstMeta => const TaskConstMeta(
        debugName: "encode_pl2_data_frame",
        argNames: ["sessionId", "chunkId", "totalChunks", "payload"],
      );

  @override
  Uint8List crateApiEncodePlcmFrame({required PlcmFrameDto frame}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_plcm_frame_dto(frame, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiEncodePlcmFrameConstMeta,
      argValues: [frame],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEncodePlcmFrameConstMeta => const TaskConstMeta(
        debugName: "encode_plcm_frame",
        argNames: ["frame"],
      );

  @override
  Uint8List crateApiEncodePlosFrame({required PlosFrameDto frame}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_plos_frame_dto(frame, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiEncodePlosFrameConstMeta,
      argValues: [frame],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEncodePlosFrameConstMeta => const TaskConstMeta(
        debugName: "encode_plos_frame",
        argNames: ["frame"],
      );

  @override
  Uint8List crateApiEncryptData(
      {required List<int> plaintext, required List<int> sessionKey}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(plaintext, serializer);
        sse_encode_list_prim_u_8_loose(sessionKey, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiEncryptDataConstMeta,
      argValues: [plaintext, sessionKey],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEncryptDataConstMeta => const TaskConstMeta(
        debugName: "encrypt_data",
        argNames: ["plaintext", "sessionKey"],
      );

  @override
  List<Uint8List>? crateApiFecDecodeBlock(
      {required int dataCount,
      required int parityCount,
      required int symbolLength,
      required List<int> erasures,
      required List<int> availableKeys,
      required List<Uint8List> availableValues}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(dataCount, serializer);
        sse_encode_u_32(parityCount, serializer);
        sse_encode_u_32(symbolLength, serializer);
        sse_encode_list_prim_u_32_loose(erasures, serializer);
        sse_encode_list_prim_u_32_loose(availableKeys, serializer);
        sse_encode_list_list_prim_u_8_strict(availableValues, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_list_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFecDecodeBlockConstMeta,
      argValues: [
        dataCount,
        parityCount,
        symbolLength,
        erasures,
        availableKeys,
        availableValues
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFecDecodeBlockConstMeta => const TaskConstMeta(
        debugName: "fec_decode_block",
        argNames: [
          "dataCount",
          "parityCount",
          "symbolLength",
          "erasures",
          "availableKeys",
          "availableValues"
        ],
      );

  @override
  List<Uint8List> crateApiFecEncodeBlock(
      {required List<Uint8List> dataSymbols,
      required int parityCount,
      required int symbolLength}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_list_prim_u_8_strict(dataSymbols, serializer);
        sse_encode_u_32(parityCount, serializer);
        sse_encode_u_32(symbolLength, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFecEncodeBlockConstMeta,
      argValues: [dataSymbols, parityCount, symbolLength],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFecEncodeBlockConstMeta => const TaskConstMeta(
        debugName: "fec_encode_block",
        argNames: ["dataSymbols", "parityCount", "symbolLength"],
      );

  @override
  ReconstructionHandle crateApiReconstructionNew() {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiReconstructionNewConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiReconstructionNewConstMeta => const TaskConstMeta(
        debugName: "reconstruction_new",
        argNames: [],
      );

  @override
  String crateApiSha256Hex({required List<int> data}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSha256HexConstMeta,
      argValues: [data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSha256HexConstMeta => const TaskConstMeta(
        debugName: "sha256_hex",
        argNames: ["data"],
      );

  @override
  bool crateApiSha256Verify(
      {required List<int> data, required String expected}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(data, serializer);
        sse_encode_String(expected, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSha256VerifyConstMeta,
      argValues: [data, expected],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSha256VerifyConstMeta => const TaskConstMeta(
        debugName: "sha256_verify",
        argNames: ["data", "expected"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_ReconstructionHandle => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_ReconstructionHandle => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle;

  @protected
  ReconstructionHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReconstructionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ReconstructionHandle
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReconstructionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ReconstructionHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReconstructionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ReconstructionHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ReconstructionHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DataChunkDto dco_decode_box_autoadd_data_chunk_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_data_chunk_dto(raw);
  }

  @protected
  PlcmFrameDto dco_decode_box_autoadd_plcm_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_plcm_frame_dto(raw);
  }

  @protected
  PlosFrameDto dco_decode_box_autoadd_plos_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_plos_frame_dto(raw);
  }

  @protected
  QualityScoreInput dco_decode_box_autoadd_quality_score_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_quality_score_input(raw);
  }

  @protected
  CompressionOutputDto dco_decode_compression_output_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CompressionOutputDto(
      originalSize: dco_decode_u_32(arr[0]),
      outputSize: dco_decode_u_32(arr[1]),
      bytes: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  DataChunkDto dco_decode_data_chunk_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return DataChunkDto(
      sessionId: dco_decode_String(arr[0]),
      chunkId: dco_decode_u_32(arr[1]),
      totalChunks: dco_decode_u_32(arr[2]),
      payload: dco_decode_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<DataChunkDto> dco_decode_list_data_chunk_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_data_chunk_dto).toList();
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<Uint8List>? dco_decode_opt_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_list_prim_u_8_strict(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  Pl2FrameDto dco_decode_pl_2_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return Pl2FrameDto(
      packetType: dco_decode_String(arr[0]),
      sessionId: dco_decode_String(arr[1]),
      seq: dco_decode_u_32(arr[2]),
      total: dco_decode_u_32(arr[3]),
      payload: dco_decode_list_prim_u_8_strict(arr[4]),
    );
  }

  @protected
  PlcmFrameDto dco_decode_plcm_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return PlcmFrameDto(
      protocolVersion: dco_decode_u_8(arr[0]),
      sessionId: dco_decode_String(arr[1]),
      frameId: dco_decode_u_32(arr[2]),
      packetId: dco_decode_u_32(arr[3]),
      packetType: dco_decode_u_8(arr[4]),
      totalPackets: dco_decode_u_32(arr[5]),
      gridSize: dco_decode_u_32(arr[6]),
      bitsPerChannel: dco_decode_u_8(arr[7]),
      payload: dco_decode_list_prim_u_8_strict(arr[8]),
      checksum: dco_decode_u_32(arr[9]),
    );
  }

  @protected
  PlosFrameDto dco_decode_plos_frame_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return PlosFrameDto(
      protocolVersion: dco_decode_u_8(arr[0]),
      sessionId: dco_decode_String(arr[1]),
      streamId: dco_decode_u_16(arr[2]),
      frameId: dco_decode_u_32(arr[3]),
      packetId: dco_decode_u_32(arr[4]),
      packetType: dco_decode_u_8(arr[5]),
      totalPackets: dco_decode_u_32(arr[6]),
      syncMarker: dco_decode_u_16(arr[7]),
      timestamp: dco_decode_u_64(arr[8]),
      gridSize: dco_decode_u_32(arr[9]),
      bitsPerCell: dco_decode_u_8(arr[10]),
      payload: dco_decode_list_prim_u_8_strict(arr[11]),
      checksum: dco_decode_u_32(arr[12]),
    );
  }

  @protected
  QualityScoreInput dco_decode_quality_score_input(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return QualityScoreInput(
      framesReceived: dco_decode_u_32(arr[0]),
      framesCorrupted: dco_decode_u_32(arr[1]),
      framesLost: dco_decode_u_32(arr[2]),
      missingPacketCount: dco_decode_u_32(arr[3]),
      framesRetried: dco_decode_u_32(arr[4]),
      detectionAccuracy: dco_decode_f_64(arr[5]),
      avgBrightness: dco_decode_f_64(arr[6]),
      detectionSuccessRate: dco_decode_f_64(arr[7]),
      fecParityGenerated: dco_decode_u_32(arr[8]),
      fecRecoverySuccessRate: dco_decode_f_64(arr[9]),
      fecParityEfficiency: dco_decode_f_64(arr[10]),
      fecOverhead: dco_decode_f_64(arr[11]),
    );
  }

  @protected
  QualityScoreOutput dco_decode_quality_score_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return QualityScoreOutput(
      score: dco_decode_f_64(arr[0]),
      frameLossFactor: dco_decode_f_64(arr[1]),
      decodeErrorFactor: dco_decode_f_64(arr[2]),
      retryFactor: dco_decode_f_64(arr[3]),
      detectionStabilityFactor: dco_decode_f_64(arr[4]),
      brightnessFactor: dco_decode_f_64(arr[5]),
      recoveryFactor: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ReconstructionHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReconstructionHandleImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ReconstructionHandle
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReconstructionHandleImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ReconstructionHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReconstructionHandleImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  ReconstructionHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ReconstructionHandleImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DataChunkDto sse_decode_box_autoadd_data_chunk_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_data_chunk_dto(deserializer));
  }

  @protected
  PlcmFrameDto sse_decode_box_autoadd_plcm_frame_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_plcm_frame_dto(deserializer));
  }

  @protected
  PlosFrameDto sse_decode_box_autoadd_plos_frame_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_plos_frame_dto(deserializer));
  }

  @protected
  QualityScoreInput sse_decode_box_autoadd_quality_score_input(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_quality_score_input(deserializer));
  }

  @protected
  CompressionOutputDto sse_decode_compression_output_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_originalSize = sse_decode_u_32(deserializer);
    var var_outputSize = sse_decode_u_32(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return CompressionOutputDto(
        originalSize: var_originalSize,
        outputSize: var_outputSize,
        bytes: var_bytes);
  }

  @protected
  DataChunkDto sse_decode_data_chunk_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_chunkId = sse_decode_u_32(deserializer);
    var var_totalChunks = sse_decode_u_32(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    return DataChunkDto(
        sessionId: var_sessionId,
        chunkId: var_chunkId,
        totalChunks: var_totalChunks,
        payload: var_payload);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<DataChunkDto> sse_decode_list_data_chunk_dto(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DataChunkDto>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_data_chunk_dto(deserializer));
    }
    return ans_;
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<Uint8List>? sse_decode_opt_list_list_prim_u_8_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Pl2FrameDto sse_decode_pl_2_frame_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_packetType = sse_decode_String(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_seq = sse_decode_u_32(deserializer);
    var var_total = sse_decode_u_32(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    return Pl2FrameDto(
        packetType: var_packetType,
        sessionId: var_sessionId,
        seq: var_seq,
        total: var_total,
        payload: var_payload);
  }

  @protected
  PlcmFrameDto sse_decode_plcm_frame_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_protocolVersion = sse_decode_u_8(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_frameId = sse_decode_u_32(deserializer);
    var var_packetId = sse_decode_u_32(deserializer);
    var var_packetType = sse_decode_u_8(deserializer);
    var var_totalPackets = sse_decode_u_32(deserializer);
    var var_gridSize = sse_decode_u_32(deserializer);
    var var_bitsPerChannel = sse_decode_u_8(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    var var_checksum = sse_decode_u_32(deserializer);
    return PlcmFrameDto(
        protocolVersion: var_protocolVersion,
        sessionId: var_sessionId,
        frameId: var_frameId,
        packetId: var_packetId,
        packetType: var_packetType,
        totalPackets: var_totalPackets,
        gridSize: var_gridSize,
        bitsPerChannel: var_bitsPerChannel,
        payload: var_payload,
        checksum: var_checksum);
  }

  @protected
  PlosFrameDto sse_decode_plos_frame_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_protocolVersion = sse_decode_u_8(deserializer);
    var var_sessionId = sse_decode_String(deserializer);
    var var_streamId = sse_decode_u_16(deserializer);
    var var_frameId = sse_decode_u_32(deserializer);
    var var_packetId = sse_decode_u_32(deserializer);
    var var_packetType = sse_decode_u_8(deserializer);
    var var_totalPackets = sse_decode_u_32(deserializer);
    var var_syncMarker = sse_decode_u_16(deserializer);
    var var_timestamp = sse_decode_u_64(deserializer);
    var var_gridSize = sse_decode_u_32(deserializer);
    var var_bitsPerCell = sse_decode_u_8(deserializer);
    var var_payload = sse_decode_list_prim_u_8_strict(deserializer);
    var var_checksum = sse_decode_u_32(deserializer);
    return PlosFrameDto(
        protocolVersion: var_protocolVersion,
        sessionId: var_sessionId,
        streamId: var_streamId,
        frameId: var_frameId,
        packetId: var_packetId,
        packetType: var_packetType,
        totalPackets: var_totalPackets,
        syncMarker: var_syncMarker,
        timestamp: var_timestamp,
        gridSize: var_gridSize,
        bitsPerCell: var_bitsPerCell,
        payload: var_payload,
        checksum: var_checksum);
  }

  @protected
  QualityScoreInput sse_decode_quality_score_input(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_framesReceived = sse_decode_u_32(deserializer);
    var var_framesCorrupted = sse_decode_u_32(deserializer);
    var var_framesLost = sse_decode_u_32(deserializer);
    var var_missingPacketCount = sse_decode_u_32(deserializer);
    var var_framesRetried = sse_decode_u_32(deserializer);
    var var_detectionAccuracy = sse_decode_f_64(deserializer);
    var var_avgBrightness = sse_decode_f_64(deserializer);
    var var_detectionSuccessRate = sse_decode_f_64(deserializer);
    var var_fecParityGenerated = sse_decode_u_32(deserializer);
    var var_fecRecoverySuccessRate = sse_decode_f_64(deserializer);
    var var_fecParityEfficiency = sse_decode_f_64(deserializer);
    var var_fecOverhead = sse_decode_f_64(deserializer);
    return QualityScoreInput(
        framesReceived: var_framesReceived,
        framesCorrupted: var_framesCorrupted,
        framesLost: var_framesLost,
        missingPacketCount: var_missingPacketCount,
        framesRetried: var_framesRetried,
        detectionAccuracy: var_detectionAccuracy,
        avgBrightness: var_avgBrightness,
        detectionSuccessRate: var_detectionSuccessRate,
        fecParityGenerated: var_fecParityGenerated,
        fecRecoverySuccessRate: var_fecRecoverySuccessRate,
        fecParityEfficiency: var_fecParityEfficiency,
        fecOverhead: var_fecOverhead);
  }

  @protected
  QualityScoreOutput sse_decode_quality_score_output(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_score = sse_decode_f_64(deserializer);
    var var_frameLossFactor = sse_decode_f_64(deserializer);
    var var_decodeErrorFactor = sse_decode_f_64(deserializer);
    var var_retryFactor = sse_decode_f_64(deserializer);
    var var_detectionStabilityFactor = sse_decode_f_64(deserializer);
    var var_brightnessFactor = sse_decode_f_64(deserializer);
    var var_recoveryFactor = sse_decode_f_64(deserializer);
    return QualityScoreOutput(
        score: var_score,
        frameLossFactor: var_frameLossFactor,
        decodeErrorFactor: var_decodeErrorFactor,
        retryFactor: var_retryFactor,
        detectionStabilityFactor: var_detectionStabilityFactor,
        brightnessFactor: var_brightnessFactor,
        recoveryFactor: var_recoveryFactor);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          ReconstructionHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ReconstructionHandleImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          ReconstructionHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ReconstructionHandleImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          ReconstructionHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ReconstructionHandleImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          ReconstructionHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as ReconstructionHandleImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_data_chunk_dto(
      DataChunkDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_data_chunk_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_plcm_frame_dto(
      PlcmFrameDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_plcm_frame_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_plos_frame_dto(
      PlosFrameDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_plos_frame_dto(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_quality_score_input(
      QualityScoreInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_quality_score_input(self, serializer);
  }

  @protected
  void sse_encode_compression_output_dto(
      CompressionOutputDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.originalSize, serializer);
    sse_encode_u_32(self.outputSize, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_data_chunk_dto(DataChunkDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_u_32(self.chunkId, serializer);
    sse_encode_u_32(self.totalChunks, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_data_chunk_dto(
      List<DataChunkDto> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_data_chunk_dto(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint32List(self is Uint32List ? self : Uint32List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_list_list_prim_u_8_strict(
      List<Uint8List>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_pl_2_frame_dto(Pl2FrameDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.packetType, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_u_32(self.seq, serializer);
    sse_encode_u_32(self.total, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
  }

  @protected
  void sse_encode_plcm_frame_dto(PlcmFrameDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.protocolVersion, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_u_32(self.frameId, serializer);
    sse_encode_u_32(self.packetId, serializer);
    sse_encode_u_8(self.packetType, serializer);
    sse_encode_u_32(self.totalPackets, serializer);
    sse_encode_u_32(self.gridSize, serializer);
    sse_encode_u_8(self.bitsPerChannel, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
    sse_encode_u_32(self.checksum, serializer);
  }

  @protected
  void sse_encode_plos_frame_dto(PlosFrameDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self.protocolVersion, serializer);
    sse_encode_String(self.sessionId, serializer);
    sse_encode_u_16(self.streamId, serializer);
    sse_encode_u_32(self.frameId, serializer);
    sse_encode_u_32(self.packetId, serializer);
    sse_encode_u_8(self.packetType, serializer);
    sse_encode_u_32(self.totalPackets, serializer);
    sse_encode_u_16(self.syncMarker, serializer);
    sse_encode_u_64(self.timestamp, serializer);
    sse_encode_u_32(self.gridSize, serializer);
    sse_encode_u_8(self.bitsPerCell, serializer);
    sse_encode_list_prim_u_8_strict(self.payload, serializer);
    sse_encode_u_32(self.checksum, serializer);
  }

  @protected
  void sse_encode_quality_score_input(
      QualityScoreInput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.framesReceived, serializer);
    sse_encode_u_32(self.framesCorrupted, serializer);
    sse_encode_u_32(self.framesLost, serializer);
    sse_encode_u_32(self.missingPacketCount, serializer);
    sse_encode_u_32(self.framesRetried, serializer);
    sse_encode_f_64(self.detectionAccuracy, serializer);
    sse_encode_f_64(self.avgBrightness, serializer);
    sse_encode_f_64(self.detectionSuccessRate, serializer);
    sse_encode_u_32(self.fecParityGenerated, serializer);
    sse_encode_f_64(self.fecRecoverySuccessRate, serializer);
    sse_encode_f_64(self.fecParityEfficiency, serializer);
    sse_encode_f_64(self.fecOverhead, serializer);
  }

  @protected
  void sse_encode_quality_score_output(
      QualityScoreOutput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.score, serializer);
    sse_encode_f_64(self.frameLossFactor, serializer);
    sse_encode_f_64(self.decodeErrorFactor, serializer);
    sse_encode_f_64(self.retryFactor, serializer);
    sse_encode_f_64(self.detectionStabilityFactor, serializer);
    sse_encode_f_64(self.brightnessFactor, serializer);
    sse_encode_f_64(self.recoveryFactor, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ReconstructionHandleImpl extends RustOpaque
    implements ReconstructionHandle {
  // Not to be used by end users
  ReconstructionHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ReconstructionHandleImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: PhotonLinkCoreApi
        .instance.api.rust_arc_increment_strong_count_ReconstructionHandle,
    rustArcDecrementStrongCount: PhotonLinkCoreApi
        .instance.api.rust_arc_decrement_strong_count_ReconstructionHandle,
    rustArcDecrementStrongCountPtr: PhotonLinkCoreApi
        .instance.api.rust_arc_decrement_strong_count_ReconstructionHandlePtr,
  );

  Future<bool> ingestData({required DataChunkDto chunk}) =>
      PhotonLinkCoreApi.instance.api
          .crateApiReconstructionHandleIngestData(that: this, chunk: chunk);

  Future<bool> isComplete() =>
      PhotonLinkCoreApi.instance.api.crateApiReconstructionHandleIsComplete(
        that: this,
      );

  Future<Uint8List?> rebuild() =>
      PhotonLinkCoreApi.instance.api.crateApiReconstructionHandleRebuild(
        that: this,
      );

  Future<void> reset() =>
      PhotonLinkCoreApi.instance.api.crateApiReconstructionHandleReset(
        that: this,
      );

  Future<bool> setMetadata(
          {required String sessionId, required int totalChunks}) =>
      PhotonLinkCoreApi.instance.api.crateApiReconstructionHandleSetMetadata(
          that: this, sessionId: sessionId, totalChunks: totalChunks);
}
