// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'diagnostics.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class PhotonLinkCoreApiApiImplPlatform
    extends BaseApiImpl<PhotonLinkCoreApiWire> {
  PhotonLinkCoreApiApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_ReconstructionHandlePtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandlePtr;

  @protected
  ReconstructionHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          dynamic raw);

  @protected
  ReconstructionHandle
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          dynamic raw);

  @protected
  ReconstructionHandle
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          dynamic raw);

  @protected
  ReconstructionHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DataChunkDto dco_decode_box_autoadd_data_chunk_dto(dynamic raw);

  @protected
  PlcmFrameDto dco_decode_box_autoadd_plcm_frame_dto(dynamic raw);

  @protected
  PlosFrameDto dco_decode_box_autoadd_plos_frame_dto(dynamic raw);

  @protected
  QualityScoreInput dco_decode_box_autoadd_quality_score_input(dynamic raw);

  @protected
  CompressionOutputDto dco_decode_compression_output_dto(dynamic raw);

  @protected
  DataChunkDto dco_decode_data_chunk_dto(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  List<DataChunkDto> dco_decode_list_data_chunk_dto(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_32_loose(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Uint8List>? dco_decode_opt_list_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  Pl2FrameDto dco_decode_pl_2_frame_dto(dynamic raw);

  @protected
  PlcmFrameDto dco_decode_plcm_frame_dto(dynamic raw);

  @protected
  PlosFrameDto dco_decode_plos_frame_dto(dynamic raw);

  @protected
  QualityScoreInput dco_decode_quality_score_input(dynamic raw);

  @protected
  QualityScoreOutput dco_decode_quality_score_output(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ReconstructionHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          SseDeserializer deserializer);

  @protected
  ReconstructionHandle
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          SseDeserializer deserializer);

  @protected
  ReconstructionHandle
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          SseDeserializer deserializer);

  @protected
  ReconstructionHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DataChunkDto sse_decode_box_autoadd_data_chunk_dto(
      SseDeserializer deserializer);

  @protected
  PlcmFrameDto sse_decode_box_autoadd_plcm_frame_dto(
      SseDeserializer deserializer);

  @protected
  PlosFrameDto sse_decode_box_autoadd_plos_frame_dto(
      SseDeserializer deserializer);

  @protected
  QualityScoreInput sse_decode_box_autoadd_quality_score_input(
      SseDeserializer deserializer);

  @protected
  CompressionOutputDto sse_decode_compression_output_dto(
      SseDeserializer deserializer);

  @protected
  DataChunkDto sse_decode_data_chunk_dto(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  List<DataChunkDto> sse_decode_list_data_chunk_dto(
      SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_32_loose(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Uint8List>? sse_decode_opt_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  Pl2FrameDto sse_decode_pl_2_frame_dto(SseDeserializer deserializer);

  @protected
  PlcmFrameDto sse_decode_plcm_frame_dto(SseDeserializer deserializer);

  @protected
  PlosFrameDto sse_decode_plos_frame_dto(SseDeserializer deserializer);

  @protected
  QualityScoreInput sse_decode_quality_score_input(
      SseDeserializer deserializer);

  @protected
  QualityScoreOutput sse_decode_quality_score_output(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          ReconstructionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          ReconstructionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          ReconstructionHandle self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
          ReconstructionHandle self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_data_chunk_dto(
      DataChunkDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_plcm_frame_dto(
      PlcmFrameDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_plos_frame_dto(
      PlosFrameDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_quality_score_input(
      QualityScoreInput self, SseSerializer serializer);

  @protected
  void sse_encode_compression_output_dto(
      CompressionOutputDto self, SseSerializer serializer);

  @protected
  void sse_encode_data_chunk_dto(DataChunkDto self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_list_data_chunk_dto(
      List<DataChunkDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_loose(
      List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_32_strict(
      Uint32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_list_prim_u_8_strict(
      List<Uint8List>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_pl_2_frame_dto(Pl2FrameDto self, SseSerializer serializer);

  @protected
  void sse_encode_plcm_frame_dto(PlcmFrameDto self, SseSerializer serializer);

  @protected
  void sse_encode_plos_frame_dto(PlosFrameDto self, SseSerializer serializer);

  @protected
  void sse_encode_quality_score_input(
      QualityScoreInput self, SseSerializer serializer);

  @protected
  void sse_encode_quality_score_output(
      QualityScoreOutput self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class PhotonLinkCoreApiWire implements BaseWire {
  factory PhotonLinkCoreApiWire.fromExternalLibrary(ExternalLibrary lib) =>
      PhotonLinkCoreApiWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  PhotonLinkCoreApiWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_photonlink_app_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandlePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_photonlink_app_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandle =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerReconstructionHandlePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
